### ISSUE TITLE
update loader-utils

### ISSUE THREAD

**Issue by Fidanze** [css-modules/generic-names#23]
loader-utils add support of base64-safe in 3.3.1

**Comment by Fidanze** [comment]
why i need it? explain

**Comment by Fidanze** [comment]
and mediafire said its dangerous file

**Comment by alexander-akait** [comment]
You can do it locally - https://github.com/css-modules/generic-names/blob/master/package.json#L29 - https://docs.npmjs.com/updating-packages-downloaded-from-the-registry

**Comment by Fidanze** [comment]
can you explain why i should do it locally? i mean why i should not do PR with this change?

**Comment by alexander-akait** [comment]
Because we use `^`

**Comment by Fidanze** [comment]
i think i should explain my situation. i use vite and i try to use css.modules.generatescopedname option. it use postcss-modules which use generic-names which use loader-utils. in readme of postcss-modules we have a link to more details of generateScopedName and by click to it i go to webpack/loader-utils where i can see that i can use base64-safe.

i understood that i can locally update package-lock.json, but how can i update this "deep" dependency package-lock.json?

**Comment by alexander-akait** [comment]
`npm update generic-names` - https://docs.npmjs.com/cli/v10/commands/npm-update
