### ISSUE TITLE
npm access

### ISSUE THREAD

**Issue by alexander-akait** [css-modules/generic-names#5]
We rewrite `css-loader` on `ICSS` and drop css modules from `css-loader` in favor `postcss-loader` with `postcss-icss-*` plugin. Can you give `npm` access to this repo for update deps?

**Comment by mightyaleksey** [comment]
@evilebottnawi sure, can you tell me your email?

Up: found you and granted an npm access to the packages to which access I had.
I guess @TrySound can help with rest of them.

**Comment by alexander-akait** [comment]
@sullenor thanks!

**Comment by alexander-akait** [comment]
@sullenor can you give github permissions?

**Comment by TrySound** [comment]
Done

**Comment by mightyaleksey** [comment]
@evilebottnawi unfortunately I have a read access, I guess @geelen can add you to the node team.
